### ISSUE TITLE
Update to Torch 2.0

### ISSUE THREAD

**Issue by vadi2** [db0/AI-Horde-Worker#110]
Please update the torch dependency from 1.14 to [2.0](https://pytorch.org/blog/pytorch-2.0-release) - in part because new torch will pull in newer cudnn, cublas and nvblas libraries which yield a 200% speed improvement on RTX 40-series cards.

**Comment by jug-dev** [comment]
We definitely must _not_ do this. If Airic gets a 200% speed boost I'll have no chance of ever catching up with him!

**Comment by jug-dev** [comment]
This has been done in the new worker.
