### ISSUE TITLE
Request: OpenSYCL/DPC++ support for multiple architectures

### ISSUE THREAD

**Issue by iamhumanipromise** [db0/AI-Horde-Worker#144]
Requesting OpenSYCL support (Or DPC++) to be able to have jobs on Intel dGPUs, iGPUs, AMD GPUs, CUDA GPUs, and more simultaneously: or working together to share resources.

**Comment by jug-dev** [comment]
SYCL isn't really relevant at the level of the software stack at which the horde worker operates.  The horde worker is relying on other libraries to do stable diffusion inference, and they in turn rely on other libraries for hardware acceleration. 

I would suggest you raise your suggestion with https://github.com/pytorch/pytorch which is essentially what is the limiting factor to what horde workers can run on using hardware acceleration.
