### ISSUE TITLE
Horde not sending jobs!

### ISSUE THREAD

**Issue by axemaster** [db0/AI-Horde-Worker#178]
I have not received a job in hours. In the Stable UI the leaderboard when sorted by MPS is all zero. Is there a problem? I could not find an existing issue for this.
Was there a recent change to the job allocation algorithm?

![image](https://user-images.githubusercontent.com/1783597/235629476-80c5f8b7-04cb-480d-be8c-1269b2b3881b.png)

ETA: Yesterday and previous I had non-stop traffic. Something has changed and not on my end.

**Comment by db0** [comment]
No problem.The dashboard is probably using an obsolete endpoint. I'm still receiving jobs on my worker. What models are you serving?

**Comment by axemaster** [comment]
F222, URPM, Deliberate.
Did the endpoint version up? I'm using the A1111 extension horde worker. Maybe it's using the wrong endpoint as well.

**Comment by axemaster** [comment]
> What models are you serving?

Which are you serving? I can switch...

**Comment by db0** [comment]
The three that you're serving should have plenty of traffic
What is your max_power?

**Comment by db0** [comment]
I just saw here https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker/issues/94 that you're using the a1111 extension. As that's unofficial, I can't offer much support. You can always use the official worker for this

**Comment by axemaster** [comment]
> What is your max_power?

286720. It's low but gets plenty of jobs usually.

The ext worked two days ago. Has there been an API change in the last two days? If so I should alert them.

I had trouble getting the official worker to run so I switched to the extension, no troubles since then until last night.

I put an issue on them as you saw, so hopefully they look into it.

**Comment by axemaster** [comment]
Closing issue will track with the one on the ext.
