### ISSUE TITLE
Selected model not found?

### ISSUE THREAD

**Issue by pastuh** [db0/AI-Horde-Worker#180]
Sometimes I see error message which looks like this: 
`Model name Lyriel requested in bridgeData is unknown to us. Please check configuration`

I know this model was selected in configuration, so why I get this error?

**Comment by db0** [comment]
@tazlin might nkow something about this

**Comment by tazlin** [comment]
The horde is transitioning to a new worker backend. The list of available models includes some models which cannot work with the legacy backend. If you select a model from this list, it will give you this error for the time being:

- Lyriel
- GuFeng
- Edge Of Realism
- Rev Animated
- 526Mix-Animated
- Neurogen
- Aurora
- CamelliaMix 2.5D
- Ether Real Mix
- DnD Map Generator
- Beautiful Realistic Asians

I apologize for the confusion. The worker update to the new syste, is coming fairly soon, and these models will be supported at that time.

**Comment by jug-dev** [comment]
Closing this as it's resolved by the imminent worker update
