### ISSUE TITLE
Forgot to login, how to continue?

### ISSUE THREAD

**Issue by pastuh** [db0/AI-Horde-Worker#181]
Registered and got API key.
After a while I logged in and got again new API key. (even used the same name)

Configured server with new API key but now receiving error `Wrong credentials to submit as this worker. (403)`

So.. how can I merge the previous and new keys?
My previous "work" is lost?

**Comment by db0** [comment]
Do you still have access to the old API key?

**Comment by pastuh** [comment]
Yes, new and old still exist

**Comment by db0** [comment]
Unfortunately there's no way to transfer workers. You can keep using the old key, or you can transfer your kudos to your new account, rename the old worker, and start the worker again with the new key.
