### ISSUE TITLE
"ModuleNotFoundError: No module named 'gradio'" when trying to run WebUI

### ISSUE THREAD

**Issue by ExCx** [db0/AI-Horde-Worker#19]
I'm on a Windows 11 machine. I cloned the repository. Ran "update-runtime" and after 30 minutes it's completed like this (I'm not sure if it's completed succesfully. Please confirm): 
![aaaa](https://user-images.githubusercontent.com/6174269/214030130-22ff0aac-1bfc-4fbe-b8d3-0a65287321fd.png)

After that, I ran the bridge-webui. But it fails to run throwing this error message continuously:
```
Traceback (most recent call last):
  File "webui.py", line 1, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
```

So what should I do now?

**Comment by db0** [comment]
It doesn't looks like the update-runtime finished. Did it return to the terminal after this because it seems it was still running to me

**Comment by ExCx** [comment]
I waited an whole hour but it stayed like this so I assumed it's finished. I tried running it again today and the same thing happened (this time in 5 minutes). What may be the issue? Should I delete and try it again?

**Comment by db0** [comment]
It looks like it's getting stuck. I don't have win11 so I'm not quite sure why it's getting stuck like this. Only thing I can suggest is leave it running for longer (although win win10 it usually takes less than 15 minutes). You can also come to our discord channel to see if someone can help you troubleshoot

**Comment by ExCx** [comment]
Ok, I ran it again and it's finished as expected now. Don't know why this happened in the first place. You can close this thread. Thanks for the quick answer.
