### ISSUE TITLE
"Highres fix" for Stable Horde?

### ISSUE THREAD

**Issue by XieBaoshi** [db0/AI-Horde-Worker#28]
Can this be implemented somehow for client and worker? (Two-stage generation when img2img is used with the same prompt for upscale to 1024p without loss of consistency)

**Comment by ResidentChief** [comment]
I have a branch on my fork that has this in testing :)  Keep your eye on the project discord for details!

**Comment by XieBaoshi** [comment]
The PR is here but no client interface supports it yet? How about ArtBot frontend or aqualxx's ui?

**Comment by db0** [comment]
This is up to each individual integrator. We don't control that.
