### ISSUE TITLE
Maintenance mode could release vram

### ISSUE THREAD

**Issue by jug-dev** [db0/AI-Horde-Worker#44]
Sometimes when I'm putting the worker into maintenance mode it's because I want to use the graphics card for something else for a minute.  Unfortunately as the worker doesn't release it's vram, one has to sometimes terminate the worker. With many models restarting the worker can take well over 30 minutes as they load into the ray object store.

It would be nice if when a worker detects it's in maintenance mode, it temporarily releases VRAM.

**Comment by jug-dev** [comment]
I'm working on this.

**Comment by AlRlC** [comment]
With the change your making, will the owner of the worker still be able to send jobs to their worker for testing purposes while in maintenance mode?

**Comment by db0** [comment]
If you're using voodoo, the VRAM should theoretically be released as it the model is only loaded into VRAM only during the period of inference.

**Comment by jug-dev** [comment]
Yes to your question AlRlC. My intention was just to have as much vram as possible released on entry to maintenance mode, not keep it released. 

I am using voodoo. But frequently when I enter maintence mode 6 or 8GB of my vram remains used. I am running a local branch which drops this to 2GB. (On Windows)

If the intended behaviour is that vram is released after inference, perhaps this is more of a bug hunt? I'll update once I've understand exactly what's happening.

**Comment by jug-dev** [comment]
This is a good (bad) example. Paused at 93% of vram still used. Resume and vram usage actually drops.

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/124293863/220429419-77788bc0-99fe-42a6-a89e-67cec96eb742.png">

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/124293863/220429651-13eff506-bda8-4a33-9ea6-ce6516515d7d.png">

**Comment by jug-dev** [comment]
Closing this as it's made irrelevant byhttps://github.com/db0/nataili/pull/1 

The worker can just be terminated and restarted quickly.
