### ISSUE TITLE
Don't try to reload the model database

### ISSUE THREAD

**Issue by jug-dev** [db0/AI-Horde-Worker#48]
In issue #45 there is an attempt to reload the model database if an unknown model is detected. This should be reverted. See PR below which does just that.

1. The previous code, although harmless, is ineffective and does nothing useful.
2. The nataili library currently provides no support for refreshing the model database once it's been instantiated. Calls into `compvis.init()` to reload the database don't propagate back up to the "super.py" aggregate class and it starts to get messy from there.

This should be reverted until nataili provides a nice simple method call to refresh the model database.

**Comment by jug-dev** [comment]
See also: https://github.com/hlky/nataili/issues/142

**Comment by hlky** [comment]
The super model manager was created specifically for horde, to replicate the model manager of v0.0.1 Nataili and minimize the changes I had to make to port AI-Horde-Worker to Nataili v0.2.x

Individual model managers do "provide a simple method call to refresh the model database" via BaseModelManager's `init()`.
