### ISSUE TITLE
Add method to serve the top X models from last day

### ISSUE THREAD

**Issue by db0** [db0/AI-Horde-Worker#62]
Add a way to override `models_to_load` with `serve_daily_top_models` which will take as an argument an integer (disabled at `-1`) which will use the horde's daily top models endpoint to compile the list of models to load.

**Comment by jug-dev** [comment]
Example bridgeData.py that does this: https://hastebin.com/share/aweceqikin.makefile

**Comment by jug-dev** [comment]
Also db0 suggested: "I also wanted to make a dynamic models lite, which changes models daily"

**Comment by db0** [comment]
cool but don't put code in bridgeData.py please :)

**Comment by jug-dev** [comment]
Working towards this in https://github.com/db0/AI-Horde-Worker/pull/71
