### ISSUE TITLE
[Feature Request] I request the ability to install pip packages on a different hard drive when updating runtime

### ISSUE THREAD

**Issue by roland3564** [db0/AI-Horde-Worker#8]
Because my storage drive is too small.

**Comment by db0** [comment]
Why don't you put this repository on the other drive?

**Comment by roland3564** [comment]
I already did put the package on the other drive, but it still installed on the main drive.

**Comment by db0** [comment]
how did you install the packages exactly?

**Comment by roland3564** [comment]
I’m using Linux, I used git to fetch a clone of the program and put it on the other drive, the program still installs on root

**Comment by db0** [comment]
```bash
cd /path/to/big/partition/mountpoint
git clone https://github.com/db0/AI-Horde-Worker.git
cd AI-Horde-Worker
update-runtime
```

this doesn't work?

**Comment by roland3564** [comment]
No it doesn't, it still says error no 28, No space left on device, despite it being empty

**Comment by roland3564** [comment]
Yep, it says the prefix on /mnt/<BigPartition>/etc..

**Comment by roland3564** [comment]
If it may be of help, I already tried installing it one time on the main drive, then erased it and tried to install it on the other drive.

**Comment by db0** [comment]
> Yep, it says the prefix on /mnt//etc..

and this mountpoint is the one with the space?

**Comment by roland3564** [comment]
Yep, it is

**Comment by db0** [comment]
The only thing I can think of is a temporary folder micromamba is storing files it's downloading. You may need to look at its documentation. Maybe there's an cli switch you can use?

**Comment by roland3564** [comment]
I don't recall having conda or micromamba installed on my system, maybe it is a python problem instead?

**Comment by db0** [comment]
micromamba is included in this repo. It's run when you use update-runtime.

**Comment by roland3564** [comment]
Solved by changing Linux distro from OpenSUSE to Linux Mint.
