### ISSUE TITLE
Model reference is retrieved every time a model is downloaded

### ISSUE THREAD

**Issue by JodanJodan** [db0/AI-Horde-Worker#81]
Model reference retrieval should be cached.

![image](https://user-images.githubusercontent.com/29270864/223541849-d167c927-f0db-4842-98f5-ef753dacb30d.png)

**Comment by jug-dev** [comment]
This was resolved some weeks ago I believe.

Could you check you're running the latest git code and have then run `update-runtime` ?

If so, could you please link your full logs/bridge.log and logs/trace.log ?

**Comment by JodanJodan** [comment]
I grabbed the latest commit and updated my runtime yesterday.
[bridge.log](https://github.com/db0/AI-Horde-Worker/files/10915079/bridge.log)

**Comment by jug-dev** [comment]
OK, I see, you are referring to the the 9 times the model reference is downloaded during worker startup I think, from looking at your logs. 

This is a nataili issue, so I've re-raised this over in the nataili project. https://github.com/db0/nataili/issues/11
