### ISSUE TITLE
"inpainting image doesn't have an alpha channel. Aborting gen"

### ISSUE THREAD

**Issue by jug-dev** [db0/AI-Horde-Worker#83]
This error causes worker to go into maintenance.

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/124293863/223656253-8d440c12-7ef7-4240-9770-d1815003e9ba.png">

**Comment by db0** [comment]
yes, I can't figure it out. Somehow the mask is being stripped during the process of uploading to R2.

**Comment by db0** [comment]
Inpainting disabled horde-wide until I figure this out

**Comment by db0** [comment]
https://github.com/db0/AI-Horde/issues/190

**Comment by jug-dev** [comment]
Fixed in the new worker.
