### ISSUE TITLE
Auto-configuration 

### ISSUE THREAD

**Issue by jug-dev** [db0/AI-Horde-Worker#91]
Add a feature which automatically configures the worker to sensible settings based on inspection of GPU, VRAM, RAM, storage space.  Or perhaps ask the user some wizard style setup questions about their wishes. Or both!

This will help ease the frequent confusion of new worker operators of where to even start.

Depends on #78

**Comment by iamhumanipromise** [comment]
I created an enhancement request [located here ](https://github.com/db0/AI-Horde-Worker/issues/144) 

SYCL seems like it is capable of detecting available workers - but not sure how scheduling, etc works out.

**Comment by jug-dev** [comment]
This has been done in the new worker.
